---
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# helm install dhcp-server -n dhcp-server

image:
  repository: 'networkboot/dhcpd'
  tag: '{{ .Chart.AppVersion }}'
  pullPolicy: 'Always'

global:
  registry: ''

config: |
  INTERFACES=
  option domain-name "SIAE-ORAN.org";
  option domain-name-servers SIAE-S1.org, SIAE-S2.org;
  
  default-lease-time 600;
  max-lease-time 7200;
  
  ddns-update-style none;
  
  authoritative;
  
  # IP range for ORAN network
  #
  subnet 10.22.17.128 netmask 255.255.255.224 {
    range 10.22.17.143 10.22.17.144;
    option routers 10.22.17.1;
    option broadcast-address 10.22.17.159;
    option time-offset 7200;
    option subnet-mask 255.255.255.224;
    option domain-name-servers 10.99.99.11, 10.99.99.12;
    default-lease-time 600;
    max-lease-time 86400;
  
    option vendor-encapsulated-options 81:04:0A:16:11:96;
  
    # OPTION 63
    # option vendor-specific-information "SIAE";
  }



